# coding=utf-8
"""
This code was generated by
\ / _    _  _|   _  _
 | (_)\/(_)(_|\/| |(/_  v1.0.0
      /       /       
"""

from twilio import values
from twilio.rest import deserialize
from twilio.rest.base import InstanceContext
from twilio.rest.base import InstanceResource
from twilio.rest.base import ListResource
from twilio.rest.v2010.account.queue.member import MemberList


class QueueList(ListResource):

    def __init__(self, domain, account_sid):
        super(QueueList, self).__init__(domain)
        
        # Path Solution
        self._instance_kwargs = {
            'account_sid': account_sid,
        }
        self._uri = "/Accounts/{account_sid}/Queues.json".format(**self._instance_kwargs)

    def read(self, limit=None, page_size=None, **kwargs):
        limits = self._domain.read_limits(limit, page_size)
        
        params = values.of({})
        params.update(kwargs)
        
        return self._domain.read(
            self,
            QueueInstance,
            self._instance_kwargs,
            'GET',
            self._uri,
            limits['limit'],
            limits['page_limit'],
            params=params,
        )

    def page(self, page_token=None, page=None, page_size=None, **kwargs):
        params = values.of({})
        params.update(kwargs)
        
        return self._domain.page(
            self,
            QueueInstance,
            self._instance_kwargs,
            'GET',
            self._uri,
            params=params,
        )

    def create(self, friendly_name=values.unset, max_size=values.unset):
        data = values.of({
            "FriendlyName": friendly_name,
            "MaxSize": max_size,
        })
        
        return self._domain.create(
            QueueInstance,
            self._instance_kwargs,
            'POST',
            self._uri,
            data=data,
        )


class QueueContext(InstanceContext):

    def __init__(self, domain, account_sid, sid):
        super(QueueContext, self).__init__(domain)
        
        # Path Solution
        self._instance_kwargs = {
            'account_sid': account_sid,
            'sid': sid,
        }
        self._uri = "/Accounts/{account_sid}/Queues/{sid}.json".format(**self._instance_kwargs)
        
        # Dependents
        self._members = None

    def fetch(self):
        return self._domain.fetch(
            QueueInstance,
            self._instance_kwargs,
            'GET',
            self._uri,
        )

    def update(self, friendly_name=values.unset, max_size=values.unset):
        data = values.of({
            "FriendlyName": friendly_name,
            "MaxSize": max_size,
        })
        
        return self._domain.update(
            QueueInstance,
            self._instance_kwargs,
            'POST',
            self._uri,
            data=data,
        )

    def delete(self):
        return self._domain.delete("delete", self._uri)

    @property
    def members(self):
        if self._members is None:
            self._members = MemberList(
                self._domain,
                account_sid=self._instance_kwargs['account_sid'],
                queue_sid=self._instance_kwargs['sid'],
            )
        return self._members


class QueueInstance(InstanceResource):

    def __init__(self, domain, payload, account_sid, sid=None):
        super(QueueInstance, self).__init__(domain)
        
        # Marshaled Properties
        self._account_sid = payload['account_sid']
        self._average_wait_time = payload['average_wait_time']
        self._current_size = payload['current_size']
        self._date_created = deserialize.iso8601_datetime(payload['date_created'])
        self._date_updated = deserialize.iso8601_datetime(payload['date_updated'])
        self._friendly_name = payload['friendly_name']
        self._max_size = payload['max_size']
        self._sid = payload['sid']
        self._uri = payload['uri']
        
        # Context
        self._lazy_context = None
        self._context_account_sid = account_sid
        self._context_sid = sid or self._sid

    @property
    def _context(self):
        if self._lazy_context is None:
            self._lazy_context = QueueContext(
                self._domain,
                self._context_account_sid,
                self._context_sid,
            )
        return self._lazy_context

    @property
    def account_sid(self):
        """ The account_sid """
        return self._account_sid

    @property
    def average_wait_time(self):
        """ Average wait time of members in the queue """
        return self._average_wait_time

    @property
    def current_size(self):
        """ The count of calls currently in the queue. """
        return self._current_size

    @property
    def date_created(self):
        """ The date_created """
        return self._date_created

    @property
    def date_updated(self):
        """ The date_updated """
        return self._date_updated

    @property
    def friendly_name(self):
        """ A user-provided string that identifies this queue. """
        return self._friendly_name

    @property
    def max_size(self):
        """ The max number of calls allowed in the queue """
        return self._max_size

    @property
    def sid(self):
        """ A string that uniquely identifies this queue """
        return self._sid

    @property
    def uri(self):
        """ The uri """
        return self._uri

    def fetch(self):
        self._context.fetch()

    def update(self, friendly_name=values.unset, max_size=values.unset):
        self._context.update(
            friendly_name=friendly_name,
            max_size=max_size,
        )

    def delete(self):
        self._context.delete()
